export const cancerHierarchy = {
  Carcinoma: [
    'Breast Cancer',
    'Lung Cancer',
    'Colon Cancer',
    'Rectal Cancer',
    'Stomach Cancer',
    'Liver Cancer',
    'Pancreatic Cancer',
    'Kidney Cancer',
    'Bladder Cancer',
    'Prostate Cancer',
    'Cervical Cancer',
    'Endometrial Cancer',
    'Ovarian Cancer',
    'Thyroid Cancer',
    'Oral Cancer',
    'Tongue Cancer',
    'Esophageal Cancer',
    'Skin (Basal Cell Carcinoma)',
    'Skin (Squamous Cell Carcinoma)',
    'Gallbladder Cancer',
    'Head & Neck Cancer',
    'Nasopharyngeal Cancer',
    'Laryngeal Cancer',
    'Salivary Gland Cancer',
  ],
  Sarcoma: [
    'Osteosarcoma',
    'Chondrosarcoma',
    'Liposarcoma',
    'Leiomyosarcoma',
    'Rhabdomyosarcoma',
    'Fibrosarcoma',
    'Angiosarcoma',
    'Synovial Sarcoma',
    'Ewing Sarcoma',
    'Kaposi Sarcoma',
  ],
  Leukemia: [
    'Acute Lymphoblastic Leukemia (ALL)',
    'Acute Myeloid Leukemia (AML)',
    'Chronic Lymphocytic Leukemia (CLL)',
    'Chronic Myeloid Leukemia (CML)',
    'Hairy Cell Leukemia',
    'Juvenine Myelomonocytic Leukemia',
  ],
  Lymphoma: [
    'Hodgkin Lymphoma',
    'Diffuse Large B-cell Lymphoma',
    'Follicular Lymphoma',
    'Mantle Cell Lymphoma',
    'Burkitt Lymphoma',
    'Marginal Zone Lymphoma',
    'Peripheral T-cell Lymphoma',
    'Anaplastic Large Cell Lymphoma',
  ],
  'Multiple Myeloma': [
    'Multiple Myeloma',
    'Smoldering Multiple Myeloma',
    'Solitary Plasmacytoma',
  ],
  Melanoma: [
    'Cutaneous Melanoma',
    'Ocular Melanoma',
    'Mucosal Melanoma',
    'Acral Lentiginous Melanoma',
  ],
  'Brain & Central Nervous System Tumors': [
    'Glioblastoma',
    'Astrocytoma',
    'Oligodendroglioma',
    'Ependymoma',
    'Meningioma',
    'Medulloblastoma',
    'Schwannoma',
    'Pituitary Tumor',
  ],
  'Germ Cell Tumors': [
    'Seminoma',
    'Non-seminoma',
    'Teratoma',
    'Yolk Sac Tumor',
    'Choriocarcinoma',
  ],
  'Neuroendocrine Tumors': [
    'Carcinoid Tumor',
    'Small Cell Lung Cancer',
    'Pancreatic Neuroendocrine Tumor',
    'Pheochromocytoma',
    'Paraganglioma',
  ],
  'Pediatric Cancers': [
    'Neuroblastoma',
    'Wilms Tumor',
    'Retinoblastoma',
    'Hepatoblastoma',
    'Pediatric Osteosarcoma',
    'Pediatric Leukemia',
  ],
  Other: [
    'Other Cancer Type',
  ],
}

export const cancerCategories = Object.keys(cancerHierarchy)
